-- GENERATED by the coteachers harness fixture script from the repo migrations that last defined each
-- function; each body (CR-stripped) equals production's prosrc md5 read on 2026-09-30 (the harness asserts it).
-- Do not edit by hand.

-- has_role: from 20260426085840_07ed6e8c-239a-4baa-935d-e78c5a297fb5.sql; body md5 4e852b30ef52ba5263c4e11d1aec8cf0
CREATE OR REPLACE FUNCTION public.has_role(_user_id UUID, _role public.app_role)
RETURNS BOOLEAN
LANGUAGE sql
STABLE SECURITY DEFINER
SET search_path = public
as $fx$
  SELECT EXISTS (SELECT 1 FROM public.user_roles WHERE user_id = _user_id AND role = _role);
$fx$;

-- award_xp: from 20260706090000_profile_gamification_phase1.sql; body md5 99d10b573c078147c4c2cf0b62b8fa18
create or replace function public.award_xp(_user uuid, _amount int, _reason text, _ref text)
returns void
language plpgsql
security definer
set search_path to 'public'
as $fx$
declare
  _inserted boolean;
begin
  if _user is null or _amount is null or _amount <= 0 then return; end if;
  insert into public.xp_events (user_id, amount, reason, ref_key)
  values (_user, _amount, _reason, _ref)
  on conflict (user_id, ref_key) do nothing;
  get diagnostics _inserted = row_count;
  if _inserted then
    insert into public.user_xp as ux (user_id, total_xp, level, updated_at)
    values (_user, _amount, public.xp_level_for(_amount), now())
    on conflict (user_id) do update
      set total_xp = ux.total_xp + excluded.total_xp,
          level = public.xp_level_for(ux.total_xp + excluded.total_xp),
          updated_at = now();
  end if;
end;
$fx$;

-- is_group_teacher: from 20260818190000_group_teachers_multi.sql; body md5 94f43876ad4f105b1a58a5120ace57ca
create or replace function public.is_group_teacher(_group_id uuid, _uid uuid)
returns boolean
language sql stable security definer set search_path = public
as $fx$
  select exists (select 1 from public.groups g where g.id = _group_id and g.teacher_id = _uid)
      or exists (select 1 from public.group_teachers gt where gt.group_id = _group_id and gt.teacher_id = _uid);
$fx$;

-- teacher_group_ids: from 20260818190000_group_teachers_multi.sql; body md5 1d12b3f354c6d021fa342edd6f127cbc
create or replace function public.teacher_group_ids(_uid uuid)
returns setof uuid
language sql stable security definer set search_path = public
as $fx$
  select id from public.groups where teacher_id = _uid
  union
  select group_id from public.group_teachers where teacher_id = _uid;
$fx$;

-- admin_group_module_submissions: from 20260926072000_fix_caller_identity_bypass.sql; body md5 408b67434cde2493c262f878a3597a41
create or replace function public.admin_group_module_submissions(p_caller_profile_id uuid default null::uuid, p_group_id uuid default null::uuid)
returns table(group_id uuid, module_id uuid, module_position integer, module_title text, total_students integer, submitted_count integer)
language plpgsql
stable
security definer
set search_path to 'public'
as $fx$
DECLARE
  -- THE FIX, in the exact shape this repo already shipped for the sibling function
  -- (20260820090000_harden_group_analytics_rpcs.sql:39-43). A REAL authenticated identity always
  -- wins; only the trusted service_role backend may assert an identity via the parameter; anything
  -- else resolves to NULL and is rejected below.
  -- Note the ordering matters even though every caller today behaves the same either way: preferring
  -- auth.uid() FIRST means a future service_role caller that also forwards a user JWT cannot assert
  -- someone else's identity. Matching the house pattern rather than inventing a second one.
  v_caller uuid := CASE
                     WHEN auth.uid() IS NOT NULL THEN auth.uid()
                     WHEN auth.role() = 'service_role' THEN p_caller_profile_id
                     ELSE NULL
                   END;
  v_is_admin boolean := false;
  v_is_teacher boolean := false;
BEGIN
  IF v_caller IS NULL THEN RAISE EXCEPTION 'auth required'; END IF;
  SELECT EXISTS (SELECT 1 FROM public.user_roles WHERE user_id = v_caller AND role = 'admin') INTO v_is_admin;
  SELECT EXISTS (SELECT 1 FROM public.user_roles WHERE user_id = v_caller AND role = 'teacher') INTO v_is_teacher;
  IF NOT (v_is_admin OR v_is_teacher) THEN RAISE EXCEPTION 'forbidden'; END IF;
  RETURN QUERY
  WITH allowed_groups AS (
    SELECT g.id, g.course_id FROM public.groups g
    WHERE (v_is_admin OR g.teacher_id = v_caller)
      AND (p_group_id IS NULL OR g.id = p_group_id)
  ),
  group_totals AS (
    SELECT p.group_id, COUNT(*)::int AS total_students
    FROM public.profiles p
    WHERE p.group_id IN (SELECT id FROM allowed_groups) AND p.archived_at IS NULL
    GROUP BY p.group_id
  ),
  group_modules AS (
    SELECT ag.id AS group_id, m.id AS module_id, m.position AS module_position, m.title AS module_title
    FROM allowed_groups ag JOIN public.modules m ON m.course_id = ag.course_id
  )
  SELECT gm.group_id, gm.module_id, gm.module_position, gm.module_title,
    COALESCE(gt.total_students, 0)::int AS total_students,
    (
      SELECT COUNT(DISTINCT p.id)::int FROM public.profiles p
      WHERE p.group_id = gm.group_id AND p.archived_at IS NULL
        AND EXISTS (
          SELECT 1 FROM public.homework_submissions hs
          JOIN public.homework_assignments ha ON ha.id = hs.assignment_id
          WHERE hs.user_id = p.id AND ha.module_id = gm.module_id AND ha.is_active = true
        )
    ) AS submitted_count
  FROM group_modules gm
  LEFT JOIN group_totals gt ON gt.group_id = gm.group_id
  ORDER BY gm.group_id, gm.module_position;
END;
$fx$;

-- teacher_group_top: from 20260820100000_harden_per_user_rpcs.sql; body md5 366b6472d9cbd0fc846ac5392736849e
CREATE OR REPLACE FUNCTION public.teacher_group_top(uid uuid, _group_id uuid, _limit integer DEFAULT 5)
 RETURNS TABLE(rank integer, first_name text, last_initial text, total_xp integer, level integer, current_streak integer, completed_lessons integer)
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
as $fx$
  with ok as (
    select exists(
      select 1 from groups g
      where g.id = _group_id
        and (g.teacher_id = uid or has_role(auth.uid(), 'admin'::app_role) or has_role(auth.uid(), 'superadmin'::app_role))
    ) and (auth.role() = 'service_role' or auth.uid() = uid
           or has_role(auth.uid(), 'admin'::app_role) or has_role(auth.uid(), 'superadmin'::app_role)) as allowed
  ),
  members as (
    select p.id, p.name, p.last_name
    from profiles p
    where p.group_id = _group_id and p.status = 'active' and p.archived_at is null
      and (select allowed from ok)
  ),
  ranked as (
    select m.id, m.name, m.last_name,
           coalesce(x.total_xp, 0) txp, coalesce(x.level, 1) lvl, coalesce(s.current_streak, 0) streak,
           row_number() over (order by coalesce(x.total_xp,0) desc, coalesce(s.current_streak,0) desc, m.id) r
    from members m
    left join user_xp x on x.user_id = m.id
    left join streaks s on s.user_id = m.id
  )
  select r.r::int, coalesce(nullif(r.name,''),'Talaba'), coalesce(left(nullif(r.last_name,''),1),''),
         r.txp, r.lvl, r.streak,
         (select count(*)::int from lesson_progress lp where lp.user_id = r.id and lp.completed_at is not null)
  from ranked r
  order by r.r
  limit _limit;
$fx$;

-- admin_export_group_csv: from 20260505205706_d33849d1-8aef-429a-ad39-d85546417272.sql; body md5 0bb5a39080b3f470f5405e41d49d085a
CREATE OR REPLACE FUNCTION public.admin_export_group_csv(_group_id uuid, _include_archived boolean DEFAULT false)
RETURNS TABLE(
  id uuid,
  name text,
  last_name text,
  email text,
  telegram_user_id bigint,
  telegram_username citext,
  role text,
  group_name text,
  first_login_at timestamptz,
  last_login_at timestamptz,
  has_logged_in boolean,
  lessons_completed integer,
  homework_avg numeric,
  status user_status,
  created_at timestamptz
)
LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path TO 'public'
as $fx$
BEGIN
  IF NOT (
    public.has_role(auth.uid(),'admin'::app_role)
    OR EXISTS (SELECT 1 FROM public.groups g WHERE g.id = _group_id AND g.teacher_id = auth.uid())
  ) THEN
    RAISE EXCEPTION 'forbidden';
  END IF;

  RETURN QUERY
  SELECT
    p.id,
    p.name,
    p.last_name,
    p.email,
    p.telegram_id AS telegram_user_id,
    p.telegram_username,
    COALESCE(
      (SELECT ur.role::text FROM public.user_roles ur
        WHERE ur.user_id = p.id
        ORDER BY CASE ur.role WHEN 'admin' THEN 1 WHEN 'teacher' THEN 2 ELSE 3 END
        LIMIT 1),
      'student'
    ) AS role,
    g.name AS group_name,
    (SELECT MIN(ae.created_at) FROM public.auth_events ae WHERE ae.user_id = p.id AND ae.event = 'sign_in') AS first_login_at,
    u.last_sign_in_at AS last_login_at,
    (u.last_sign_in_at IS NOT NULL) AS has_logged_in,
    COALESCE((SELECT COUNT(*)::int FROM public.lesson_progress lp WHERE lp.user_id = p.id AND lp.completed_at IS NOT NULL), 0) AS lessons_completed,
    (SELECT ROUND(AVG(hs.score)::numeric, 2) FROM public.homework_submissions hs WHERE hs.user_id = p.id AND hs.score IS NOT NULL) AS homework_avg,
    p.status,
    p.created_at
  FROM public.profiles p
  LEFT JOIN auth.users u ON u.id = p.id
  LEFT JOIN public.groups g ON g.id = p.group_id
  WHERE p.group_id = _group_id
    AND (_include_archived OR (p.status = 'active' AND p.archived_at IS NULL));
END;
$fx$;

-- admin_dashboard_students: from 20260613100000_admin_dashboard_students_rpc.sql; body md5 b5588f00d420a8fcbe759c74a63ba33f
CREATE OR REPLACE FUNCTION public.admin_dashboard_students(_course_id uuid, _since30 timestamptz)
RETURNS TABLE(
  id uuid,
  name text,
  last_name text,
  telegram_username citext,
  telegram_id bigint,
  email text,
  created_at timestamptz,
  last_sign_in_at timestamptz,
  last_auth_at timestamptz,
  last_lesson_at timestamptz,
  logins_30d int,
  course_completed boolean
)
LANGUAGE plpgsql
STABLE SECURITY DEFINER
SET search_path = public
as $fx$
DECLARE
  uid uuid := auth.uid();
  is_admin boolean;
  is_teacher boolean;
  total_lessons int;
BEGIN
  IF uid IS NULL THEN RAISE EXCEPTION 'forbidden'; END IF;
  is_admin := public.has_role(uid, 'admin'::app_role) OR public.has_role(uid, 'superadmin'::app_role);
  is_teacher := public.has_role(uid, 'teacher'::app_role);
  IF NOT (is_admin OR is_teacher) THEN RAISE EXCEPTION 'forbidden'; END IF;

  SELECT count(*) INTO total_lessons
  FROM public.lessons l
  JOIN public.modules m ON m.id = l.module_id
  WHERE m.course_id = _course_id AND l.published;

  RETURN QUERY
  SELECT
    p.id, p.name, p.last_name, p.telegram_username, p.telegram_id, p.email, p.created_at,
    u.last_sign_in_at,
    (SELECT max(ae.created_at) FROM public.auth_events ae
       WHERE ae.user_id = p.id AND ae.created_at >= _since30),
    (SELECT max(lp.updated_at) FROM public.lesson_progress lp
       WHERE lp.user_id = p.id AND lp.updated_at >= _since30),
    (SELECT count(*)::int FROM public.auth_events ae
       WHERE ae.user_id = p.id AND ae.created_at >= _since30 AND ae.event IN ('sign_in','login')),
    (total_lessons > 0 AND (
       SELECT count(DISTINCT lp.lesson_id) FROM public.lesson_progress lp
       JOIN public.lessons l ON l.id = lp.lesson_id
       JOIN public.modules m ON m.id = l.module_id
       WHERE lp.user_id = p.id AND m.course_id = _course_id AND l.published AND lp.completed_at IS NOT NULL
     ) >= total_lessons)
  FROM public.profiles p
  LEFT JOIN auth.users u ON u.id = p.id
  WHERE p.status = 'active'
    AND p.archived_at IS NULL
    AND NOT EXISTS (
      SELECT 1 FROM public.user_roles ur
      WHERE ur.user_id = p.id
        AND ur.role IN ('admin'::app_role, 'superadmin'::app_role, 'teacher'::app_role)
    )
    AND (
      is_admin
      OR (is_teacher AND p.group_id IN (SELECT g.id FROM public.groups g WHERE g.teacher_id = uid))
    )
  ORDER BY p.created_at DESC;
END;
$fx$;

-- staff_recent_auth_events: from 20260502222446_c87c8936-ce0d-4622-937d-43e0c7f504e3.sql; body md5 9259b47f6108b106a2bd73965f63f96b
CREATE OR REPLACE FUNCTION public.staff_recent_auth_events(_since timestamptz)
RETURNS TABLE(user_id uuid, created_at timestamptz)
LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = public
as $fx$
DECLARE uid uuid := auth.uid();
DECLARE is_admin_user boolean := public.has_role(uid, 'admin'::app_role);
DECLARE is_teacher_user boolean := public.has_role(uid, 'teacher'::app_role);
BEGIN
  IF NOT (is_admin_user OR is_teacher_user) THEN RAISE EXCEPTION 'forbidden'; END IF;
  IF is_admin_user THEN
    RETURN QUERY SELECT e.user_id, e.created_at FROM public.auth_events e WHERE e.created_at >= _since LIMIT 50000;
  ELSE
    RETURN QUERY
      SELECT e.user_id, e.created_at FROM public.auth_events e
      WHERE e.created_at >= _since
        AND e.user_id IN (SELECT p.id FROM public.profiles p WHERE p.group_id IN (SELECT g.id FROM public.groups g WHERE g.teacher_id = uid))
      LIMIT 50000;
  END IF;
END;
$fx$;

-- staff_recent_lesson_progress: from 20260502222446_c87c8936-ce0d-4622-937d-43e0c7f504e3.sql; body md5 1f77cf8273ba4e35b7d31348d3dd8b80
CREATE OR REPLACE FUNCTION public.staff_recent_lesson_progress(_since timestamptz)
RETURNS TABLE(user_id uuid, lesson_id uuid, updated_at timestamptz, completed_at timestamptz)
LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = public
as $fx$
DECLARE uid uuid := auth.uid();
DECLARE is_admin_user boolean := public.has_role(uid, 'admin'::app_role);
DECLARE is_teacher_user boolean := public.has_role(uid, 'teacher'::app_role);
BEGIN
  IF NOT (is_admin_user OR is_teacher_user) THEN RAISE EXCEPTION 'forbidden'; END IF;
  IF is_admin_user THEN
    RETURN QUERY SELECT lp.user_id, lp.lesson_id, lp.updated_at, lp.completed_at
                 FROM public.lesson_progress lp WHERE lp.updated_at >= _since LIMIT 100000;
  ELSE
    RETURN QUERY
      SELECT lp.user_id, lp.lesson_id, lp.updated_at, lp.completed_at
      FROM public.lesson_progress lp
      WHERE lp.updated_at >= _since
        AND lp.user_id IN (SELECT p.id FROM public.profiles p WHERE p.group_id IN (SELECT g.id FROM public.groups g WHERE g.teacher_id = uid))
      LIMIT 100000;
  END IF;
END;
$fx$;

-- staff_top_students: from 20260502225517_1ffcf65a-4e12-4b87-9045-f6d73ab3aaf5.sql; body md5 86cade8d4d73a31fa5403ef510ff664e
CREATE OR REPLACE FUNCTION public.staff_top_students(_lim int DEFAULT 10)
RETURNS TABLE(id uuid, name text, telegram_username citext, completed_lessons int, avg_score int, last_activity_at timestamptz)
LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = public
as $fx$
DECLARE uid uuid := auth.uid(); is_admin boolean := public.has_role(uid,'admin'::app_role);
BEGIN
  RETURN QUERY
  SELECT p.id, p.name, p.telegram_username,
    (SELECT count(*)::int FROM public.lesson_progress lp WHERE lp.user_id = p.id AND lp.completed_at IS NOT NULL) AS completed_lessons,
    (SELECT COALESCE(round(avg(qa.score))::int,0) FROM public.quiz_attempts qa WHERE qa.user_id = p.id) AS avg_score,
    (SELECT max(lp.updated_at) FROM public.lesson_progress lp WHERE lp.user_id = p.id) AS last_activity_at
  FROM public.profiles p
  WHERE
    CASE WHEN is_admin THEN true
         ELSE p.group_id IN (SELECT g.id FROM public.groups g WHERE g.teacher_id = uid)
    END
    AND NOT EXISTS (SELECT 1 FROM public.user_roles ur WHERE ur.user_id = p.id AND ur.role = 'admin')
  ORDER BY completed_lessons DESC, avg_score DESC NULLS LAST
  LIMIT _lim;
END;
$fx$;

-- admin_teacher_groups: from 20260619150000_admin_teacher_detail.sql; body md5 b274f70dbab1fc600562ae87ac36e451
CREATE OR REPLACE FUNCTION public.admin_teacher_groups(p_teacher_id uuid, p_days int DEFAULT 30, p_sla_min int DEFAULT 120)
RETURNS TABLE(group_id uuid, group_name text, students int, questions int, answered_in_sla int,
              response_rate numeric, wait_med_min numeric, graded int, ungraded int)
LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = public as $fx$
DECLARE _from timestamptz := now() - make_interval(days => p_days);
BEGIN
  IF NOT has_role(auth.uid(), 'admin'::app_role) THEN RAISE EXCEPTION 'admin only'; END IF;
  RETURN QUERY
  WITH staff_ids AS (
    SELECT DISTINCT ur.user_id AS sid FROM user_roles ur
    WHERE ur.role IN ('teacher'::app_role, 'admin'::app_role, 'superadmin'::app_role)
  ),
  tg AS (SELECT id, name, homework_topic_id FROM groups WHERE teacher_id = p_teacher_id),
  st AS (SELECT tg.id AS gid, count(*)::int AS students
         FROM tg JOIN profiles pr ON pr.group_id = tg.id AND pr.status = 'active' GROUP BY tg.id),
  dmsgs AS (
    SELECT gme.group_id AS gid, gme.telegram_chat_id AS chat, gme.telegram_thread_id AS thread,
      gme.sent_at, (gme.profile_id IN (SELECT sid FROM staff_ids)) AS is_staff
    FROM group_message_events gme
    JOIN tg ON tg.id = gme.group_id
    WHERE gme.sent_at >= _from AND gme.telegram_thread_id IS NOT NULL
      AND gme.profile_id IS NOT NULL AND gme.module_id IS NULL
      AND (tg.homework_topic_id IS NULL OR gme.telegram_thread_id <> tg.homework_topic_id)
  ),
  dmsgs_next AS (
    SELECT gid, sent_at, is_staff,
      min(CASE WHEN is_staff THEN sent_at END) OVER (
        PARTITION BY chat, thread ORDER BY sent_at DESC ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
      ) AS next_staff_at
    FROM dmsgs
  ),
  qa AS (
    SELECT gid, next_staff_at AS a_at,
      EXTRACT(EPOCH FROM (next_staff_at - sent_at)) / 60.0 AS wait_min
    FROM dmsgs_next WHERE NOT is_staff
  ),
  qa_agg AS (
    SELECT gid, count(*)::int AS questions,
      count(*) FILTER (WHERE a_at IS NOT NULL AND wait_min <= p_sla_min)::int AS answered_in_sla,
      round(percentile_cont(0.5) WITHIN GROUP (ORDER BY wait_min)
            FILTER (WHERE a_at IS NOT NULL)::numeric, 1) AS wait_med_min
    FROM qa GROUP BY gid
  ),
  grade AS (
    SELECT pr.group_id AS gid,
      count(*) FILTER (WHERE hs.scored_by = p_teacher_id AND hs.scored_at >= _from)::int AS graded,
      count(*) FILTER (WHERE hs.score IS NULL AND hs.submitted_at IS NOT NULL)::int AS ungraded
    FROM homework_submissions hs JOIN profiles pr ON pr.id = hs.user_id
    WHERE pr.group_id IN (SELECT id FROM tg) GROUP BY pr.group_id
  )
  SELECT tg.id::uuid, tg.name::text,
    COALESCE(st.students, 0)::int,
    COALESCE(q.questions, 0)::int,
    COALESCE(q.answered_in_sla, 0)::int,
    (CASE WHEN COALESCE(q.questions, 0) > 0 THEN round(100.0 * q.answered_in_sla / q.questions, 0) ELSE NULL END)::numeric,
    q.wait_med_min::numeric,
    COALESCE(gr.graded, 0)::int,
    COALESCE(gr.ungraded, 0)::int
  FROM tg
  LEFT JOIN st ON st.gid = tg.id
  LEFT JOIN qa_agg q ON q.gid = tg.id
  LEFT JOIN grade gr ON gr.gid = tg.id
  ORDER BY tg.name;
END;
$fx$;

-- admin_teacher_unanswered: from 20260619150000_admin_teacher_detail.sql; body md5 2f6119c2faea16cb0815275379f81173
CREATE OR REPLACE FUNCTION public.admin_teacher_unanswered(p_teacher_id uuid, p_days int DEFAULT 30, p_sla_min int DEFAULT 120)
RETURNS TABLE(group_name text, student_name text, asked_at timestamptz, waited_min numeric, answered boolean)
LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = public as $fx$
BEGIN
  IF NOT has_role(auth.uid(), 'admin'::app_role) THEN RAISE EXCEPTION 'admin only'; END IF;
  RETURN QUERY
  WITH staff_ids AS (
    SELECT DISTINCT ur.user_id AS sid FROM user_roles ur
    WHERE ur.role IN ('teacher'::app_role, 'admin'::app_role, 'superadmin'::app_role)
  ),
  tg AS (SELECT id, name, homework_topic_id FROM groups WHERE teacher_id = p_teacher_id),
  dmsgs AS (
    SELECT gme.group_id AS gid, gme.telegram_chat_id AS chat, gme.telegram_thread_id AS thread,
      gme.sent_at, gme.profile_id, (gme.profile_id IN (SELECT sid FROM staff_ids)) AS is_staff
    FROM group_message_events gme
    JOIN tg ON tg.id = gme.group_id
    WHERE gme.sent_at >= now() - make_interval(days => p_days)
      AND gme.telegram_thread_id IS NOT NULL AND gme.profile_id IS NOT NULL
      AND gme.module_id IS NULL
      AND (tg.homework_topic_id IS NULL OR gme.telegram_thread_id <> tg.homework_topic_id)
  ),
  dmsgs_next AS (
    SELECT d.*, min(CASE WHEN is_staff THEN sent_at END) OVER (
      PARTITION BY chat, thread ORDER BY sent_at DESC ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS next_staff_at
    FROM dmsgs d
  )
  SELECT tg.name::text,
    (COALESCE(NULLIF(TRIM(pr.name || ' ' || COALESCE(pr.last_name, '')), ''), pr.email, '—'))::text AS student_name,
    m.sent_at::timestamptz AS asked_at,
    round(EXTRACT(EPOCH FROM (COALESCE(m.next_staff_at, now()) - m.sent_at)) / 60.0, 0)::numeric AS waited_min,
    (m.next_staff_at IS NOT NULL)::boolean AS answered
  FROM dmsgs_next m
  JOIN tg ON tg.id = m.gid
  LEFT JOIN profiles pr ON pr.id = m.profile_id
  WHERE NOT m.is_staff
    AND (m.next_staff_at IS NULL OR EXTRACT(EPOCH FROM (m.next_staff_at - m.sent_at)) / 60.0 > p_sla_min)
  ORDER BY m.sent_at DESC
  LIMIT 100;
END;
$fx$;

-- analytics_teacher_quality: from 20260503071703_4b197a2f-17a1-42c4-b08c-149a88f57038.sql; body md5 896a8f390ba4222ff9ea28f5ada6b087
CREATE OR REPLACE FUNCTION public.analytics_teacher_quality(_min_students int DEFAULT 5)
RETURNS TABLE(
  teacher_id uuid,
  teacher_name text,
  teacher_email text,
  students_count bigint,
  active_7d_pct numeric,
  avg_completion_pct numeric,
  avg_homework_score numeric,
  finished_course bigint,
  quality_score numeric
)
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public as $fx$
  WITH
    teachers AS (
      SELECT g.teacher_id, g.id AS group_id
        FROM public.groups g
       WHERE g.teacher_id IS NOT NULL
    ),
    members AS (
      SELECT t.teacher_id, p.id AS user_id
        FROM teachers t
        JOIN public.profiles p ON p.group_id = t.group_id
    ),
    teacher_students AS (
      SELECT teacher_id, COUNT(DISTINCT user_id) AS students_count FROM members GROUP BY teacher_id
    ),
    active_7d AS (
      SELECT m.teacher_id, COUNT(DISTINCT lp.user_id) AS active_count
        FROM members m
        JOIN public.lesson_progress lp ON lp.user_id = m.user_id
       WHERE lp.updated_at >= now() - interval '7 days'
       GROUP BY m.teacher_id
    ),
    total_pub_lessons AS (
      SELECT COUNT(*)::numeric AS n
        FROM public.lessons l
        JOIN public.modules mo ON mo.id = l.module_id
        JOIN public.courses c ON c.id = mo.course_id AND c.published
       WHERE l.published
    ),
    user_completion AS (
      SELECT m.teacher_id, m.user_id,
             COUNT(DISTINCT lp.lesson_id) FILTER (WHERE lp.completed_at IS NOT NULL) AS done
        FROM members m
        LEFT JOIN public.lesson_progress lp ON lp.user_id = m.user_id
        GROUP BY m.teacher_id, m.user_id
    ),
    completion_avg AS (
      SELECT teacher_id,
             ROUND(AVG(LEAST(done::numeric / NULLIF((SELECT n FROM total_pub_lessons), 0), 1) * 100), 1) AS avg_completion_pct,
             COUNT(*) FILTER (WHERE done >= (SELECT n FROM total_pub_lessons)) AS finished_course
        FROM user_completion
       GROUP BY teacher_id
    ),
    hw AS (
      SELECT m.teacher_id, ROUND(AVG(hs.score)::numeric, 2) AS avg_hw
        FROM members m
        JOIN public.homework_submissions hs ON hs.user_id = m.user_id
       WHERE hs.score IS NOT NULL
       GROUP BY m.teacher_id
    ),
    profs AS (
      SELECT id, COALESCE(NULLIF(TRIM(CONCAT_WS(' ', name, last_name)), ''), email) AS teacher_name, email
        FROM public.profiles
    )
  SELECT
    ts.teacher_id,
    pr.teacher_name,
    pr.email AS teacher_email,
    ts.students_count,
    ROUND(COALESCE(ac.active_count, 0)::numeric / NULLIF(ts.students_count, 0) * 100, 1) AS active_7d_pct,
    COALESCE(ca.avg_completion_pct, 0) AS avg_completion_pct,
    COALESCE(hw.avg_hw, 0) AS avg_homework_score,
    COALESCE(ca.finished_course, 0) AS finished_course,
    /* composite: 40% completion, 30% activity, 20% homework, 10% finishers */
    ROUND(
      COALESCE(ca.avg_completion_pct, 0) * 0.4
      + COALESCE(ac.active_count::numeric / NULLIF(ts.students_count, 0) * 100, 0) * 0.3
      + COALESCE(hw.avg_hw, 0) * 10 * 0.2
      + LEAST(COALESCE(ca.finished_course, 0)::numeric / NULLIF(ts.students_count, 0) * 100, 100) * 0.1
    , 1) AS quality_score
  FROM teacher_students ts
  LEFT JOIN active_7d ac ON ac.teacher_id = ts.teacher_id
  LEFT JOIN completion_avg ca ON ca.teacher_id = ts.teacher_id
  LEFT JOIN hw ON hw.teacher_id = ts.teacher_id
  LEFT JOIN profs pr ON pr.id = ts.teacher_id
  WHERE has_role(auth.uid(), 'admin'::app_role)
    AND ts.students_count >= COALESCE(_min_students, 5)
  ORDER BY quality_score DESC NULLS LAST;
$fx$;

-- admin_teacher_stats: from 20260619140000_admin_teacher_stats.sql; body md5 a22a27311707a2d0362609f9e91ce5eb
CREATE OR REPLACE FUNCTION public.admin_teacher_stats(p_days int DEFAULT 30, p_sla_min int DEFAULT 120)
RETURNS TABLE(
  teacher_id uuid,
  name text,
  telegram_username text,
  groups_taught int,
  students int,
  active_days int,
  days_off int,
  avg_active_hours numeric,
  last_active timestamptz,
  msgs_sent int,
  questions int,
  answered_in_sla int,
  response_rate numeric,
  wait_med_min numeric,
  unanswered int,
  graded int,
  grading_med_min numeric,
  ungraded_backlog int
)
LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = public as $fx$
DECLARE
  _from timestamptz := now() - make_interval(days => p_days);
BEGIN
  IF NOT has_role(auth.uid(), 'admin'::app_role) THEN
    RAISE EXCEPTION 'admin only';
  END IF;

  RETURN QUERY
  WITH teachers AS (
    SELECT DISTINCT ur.user_id AS tid FROM user_roles ur WHERE ur.role = 'teacher'::app_role
  ),
  staff_ids AS (
    SELECT DISTINCT ur.user_id AS sid FROM user_roles ur
    WHERE ur.role IN ('teacher'::app_role, 'admin'::app_role, 'superadmin'::app_role)
  ),
  tgroups AS (  -- groups each teacher owns
    SELECT g.id AS group_id, g.teacher_id AS tid FROM groups g WHERE g.teacher_id IS NOT NULL
  ),
  gcount AS (SELECT tid, count(*)::int AS groups_taught FROM tgroups GROUP BY tid),
  gstudents AS (
    SELECT tg.tid, count(DISTINCT pr.id)::int AS students
    FROM tgroups tg JOIN profiles pr ON pr.group_id = tg.group_id AND pr.status = 'active'
    GROUP BY tg.tid
  ),
  msgs AS (
    SELECT gme.profile_id AS tid, count(*)::int AS msgs_sent
    FROM group_message_events gme
    WHERE gme.sent_at >= _from AND gme.profile_id IN (SELECT tid FROM teachers)
    GROUP BY gme.profile_id
  ),
  -- activity = any teacher signal (group message, grading, web login)
  activity AS (
    SELECT gme.profile_id AS tid, gme.sent_at AS ts
      FROM group_message_events gme
      WHERE gme.sent_at >= _from AND gme.profile_id IN (SELECT tid FROM teachers)
    UNION ALL
    SELECT hs.scored_by AS tid, hs.scored_at AS ts
      FROM homework_submissions hs
      WHERE hs.scored_at >= _from AND hs.scored_by IN (SELECT tid FROM teachers)
    UNION ALL
    SELECT ae.user_id AS tid, ae.created_at AS ts
      FROM auth_events ae
      WHERE ae.created_at >= _from AND ae.user_id IN (SELECT tid FROM teachers)
  ),
  act_agg AS (
    SELECT tid,
      count(DISTINCT (ts AT TIME ZONE 'Asia/Tashkent')::date)::int AS active_days,
      count(DISTINCT date_trunc('hour', ts AT TIME ZONE 'Asia/Tashkent'))::int AS active_hour_buckets,
      max(ts) AS last_active
    FROM activity GROUP BY tid
  ),
  grading AS (
    SELECT hs.scored_by AS tid,
      count(*)::int AS graded,
      round(percentile_cont(0.5) WITHIN GROUP (
        ORDER BY EXTRACT(EPOCH FROM (hs.scored_at - hs.submitted_at)) / 60.0)::numeric, 1) AS grading_med_min
    FROM homework_submissions hs
    WHERE hs.scored_at >= _from AND hs.scored_by IN (SELECT tid FROM teachers) AND hs.submitted_at IS NOT NULL
    GROUP BY hs.scored_by
  ),
  backlog AS (
    SELECT tg.tid, count(*)::int AS ungraded_backlog
    FROM homework_submissions hs
    JOIN profiles pr ON pr.id = hs.user_id
    JOIN tgroups tg ON tg.group_id = pr.group_id
    WHERE hs.score IS NULL AND hs.submitted_at IS NOT NULL
    GROUP BY tg.tid
  ),
  -- Student questions in DISCUSSION topics + time to the next staff reply. Computed with a fast
  -- running-min window (suffix min of staff timestamps per topic) instead of a per-message LATERAL,
  -- which exceeded statement_timeout. Homework topics excluded (per-module via module_id, shared via
  -- homework_topic_id).
  dmsgs AS (
    SELECT g.teacher_id AS tid, gme.telegram_chat_id AS chat, gme.telegram_thread_id AS thread,
      gme.sent_at, (gme.profile_id IN (SELECT sid FROM staff_ids)) AS is_staff
    FROM group_message_events gme
    JOIN groups g ON g.id = gme.group_id AND g.teacher_id IS NOT NULL
    WHERE gme.sent_at >= _from
      AND gme.telegram_thread_id IS NOT NULL
      AND gme.profile_id IS NOT NULL
      AND gme.module_id IS NULL
      AND (g.homework_topic_id IS NULL OR gme.telegram_thread_id <> g.homework_topic_id)
  ),
  dmsgs_next AS (
    SELECT tid, sent_at, is_staff,
      min(CASE WHEN is_staff THEN sent_at END) OVER (
        PARTITION BY chat, thread ORDER BY sent_at DESC
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
      ) AS next_staff_at
    FROM dmsgs
  ),
  qa AS (
    SELECT tid, next_staff_at AS a_at,
      EXTRACT(EPOCH FROM (next_staff_at - sent_at)) / 60.0 AS wait_min
    FROM dmsgs_next
    WHERE NOT is_staff
  ),
  qa_agg AS (
    SELECT tid,
      count(*)::int AS questions,
      count(*) FILTER (WHERE a_at IS NOT NULL AND wait_min <= p_sla_min)::int AS answered_in_sla,
      -- median wait over ALL answered questions (incl. late) so a slow teacher's typical wait is honest
      round(percentile_cont(0.5) WITHIN GROUP (ORDER BY wait_min)
            FILTER (WHERE a_at IS NOT NULL)::numeric, 1) AS wait_med_min
    FROM qa GROUP BY tid
  )
  -- Explicit casts on every column so the row structure provably matches RETURNS TABLE
  -- (avoids "structure of query does not match function result type" from int/bigint/numeric drift).
  SELECT
    t.tid::uuid AS teacher_id,
    (COALESCE(NULLIF(TRIM(CONCAT(p.name, ' ', COALESCE(p.last_name, ''))), ''), p.email))::text AS name,
    p.telegram_username::text,
    COALESCE(gc.groups_taught, 0)::int,
    COALESCE(gs.students, 0)::int,
    COALESCE(aa.active_days, 0)::int,
    GREATEST(p_days - COALESCE(aa.active_days, 0), 0)::int AS days_off,
    (CASE WHEN COALESCE(aa.active_days, 0) > 0
         THEN round(aa.active_hour_buckets::numeric / aa.active_days, 1) ELSE 0 END)::numeric AS avg_active_hours,
    aa.last_active::timestamptz,
    COALESCE(m.msgs_sent, 0)::int,
    COALESCE(q.questions, 0)::int,
    COALESCE(q.answered_in_sla, 0)::int,
    (CASE WHEN COALESCE(q.questions, 0) > 0
         THEN round(100.0 * q.answered_in_sla / q.questions, 0) ELSE NULL END)::numeric AS response_rate,
    q.wait_med_min::numeric,
    (COALESCE(q.questions, 0) - COALESCE(q.answered_in_sla, 0))::int AS unanswered,
    COALESCE(gr.graded, 0)::int,
    gr.grading_med_min::numeric,
    COALESCE(bl.ungraded_backlog, 0)::int
  FROM teachers t
  JOIN profiles p ON p.id = t.tid
  LEFT JOIN gcount gc ON gc.tid = t.tid
  LEFT JOIN gstudents gs ON gs.tid = t.tid
  LEFT JOIN act_agg aa ON aa.tid = t.tid
  LEFT JOIN msgs m ON m.tid = t.tid
  LEFT JOIN grading gr ON gr.tid = t.tid
  LEFT JOIN backlog bl ON bl.tid = t.tid
  LEFT JOIN qa_agg q ON q.tid = t.tid
  ORDER BY name;
END;
$fx$;

-- admin_teacher_weekly: from 20260925062000_teacher_signals_topic_guard.sql; body md5 ea30477a239b98d00ce12107b88ada59
CREATE OR REPLACE FUNCTION public.admin_teacher_weekly(p_days int DEFAULT 7, p_course_id uuid DEFAULT NULL)
RETURNS TABLE(
  teacher_id uuid, name text, telegram_username text,
  group_id uuid, group_name text,
  active_days int, days_window int,
  active_min_by_day int[], week_active_min int,
  messages_by_day int[], week_messages int,
  questions int, answered int, answer_rate numeric, median_wait_min numeric,
  graded int, grading_med_min numeric, ungraded_backlog int,
  avg_score_pct numeric, pct_top numeric, feedback_rate numeric,
  resubmit_rate numeric, oldest_pending_hours numeric,
  last_active timestamptz
)
LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = public as $fx$
#variable_conflict use_column
DECLARE
  _today date := (now() AT TIME ZONE 'Asia/Tashkent')::date;
  _from  timestamptz := now() - make_interval(days => p_days);
BEGIN
  IF NOT has_role(auth.uid(), 'admin'::app_role) THEN RAISE EXCEPTION 'admin only'; END IF;
  RETURN QUERY
  WITH teachers AS (
    SELECT DISTINCT ur.user_id AS tid FROM user_roles ur WHERE ur.role = 'teacher'::app_role
  ),
  staff_ids AS (
    SELECT DISTINCT ur.user_id AS sid FROM user_roles ur
    WHERE ur.role IN ('teacher'::app_role, 'admin'::app_role, 'superadmin'::app_role)
  ),
  -- one (teacher, group) unit per group a teacher is assigned to that has ANY chat history (skips
  -- empty placeholder groups). t_tgid = the teacher's own telegram account (for named teachers).
  -- p_course_id (when given) restricts to that course's groups → teachers OF that course only.
  tg AS (
    SELECT g.id AS gid, g.name AS gname, g.teacher_id AS tid, p.telegram_id AS t_tgid
    FROM groups g
    JOIN teachers t ON t.tid = g.teacher_id
    JOIN profiles p ON p.id = g.teacher_id
    WHERE EXISTS (SELECT 1 FROM group_message_events e WHERE e.group_id = g.id)
      AND (p_course_id IS NULL OR g.course_id = p_course_id)
  ),
  days AS (SELECT gs::date AS d FROM generate_series(_today - (p_days - 1), _today, interval '1 day') gs),
  pair_msgs AS (
    SELECT tg.tid, tg.gid,
      (e.sent_at AT TIME ZONE 'Asia/Tashkent')::date AS d,
      e.sent_at - lag(e.sent_at) OVER (PARTITION BY tg.tid, tg.gid ORDER BY e.sent_at) AS gap
    FROM group_message_events e
    JOIN tg ON tg.gid = e.group_id
    WHERE (e.sent_at AT TIME ZONE 'Asia/Tashkent')::date BETWEEN _today - (p_days - 1) AND _today
      AND (e.is_anon_admin OR (tg.t_tgid IS NOT NULL AND e.telegram_user_id = tg.t_tgid))
  ),
  pair_contrib AS (
    SELECT tid, gid, d,
      (CASE WHEN gap IS NOT NULL AND gap <= interval '10 minutes' THEN extract(epoch FROM gap) ELSE 0 END
       + CASE WHEN gap IS NULL OR gap > interval '10 minutes' THEN 60 ELSE 0 END) AS secs
    FROM pair_msgs
  ),
  pair_day AS (
    SELECT tid, gid, d, count(*)::int AS mc, round(sum(secs) / 60.0)::int AS am
    FROM pair_contrib GROUP BY tid, gid, d
  ),
  pair_grid AS (
    SELECT tg.gid, tg.tid, d.d, COALESCE(pd.am, 0) AS am, COALESCE(pd.mc, 0) AS mc
    FROM tg CROSS JOIN days d
    LEFT JOIN pair_day pd ON pd.tid = tg.tid AND pd.gid = tg.gid AND pd.d = d.d
  ),
  hours_agg AS (
    SELECT gid, tid,
      array_agg(am ORDER BY d) AS active_min_by_day,
      array_agg(mc ORDER BY d) AS messages_by_day,
      sum(am)::int AS week_active_min,
      sum(mc)::int AS week_messages,
      count(*) FILTER (WHERE mc > 0)::int AS active_days
    FROM pair_grid GROUP BY gid, tid
  ),
  dq AS (
    SELECT tg.tid, tg.gid, gme.telegram_chat_id AS chat, gme.telegram_thread_id AS thread, gme.sent_at AS q_at
    FROM group_message_events gme
    JOIN tg ON tg.gid = gme.group_id
    WHERE gme.sent_at >= _from
      AND gme.profile_id IS NOT NULL AND gme.profile_id NOT IN (SELECT sid FROM staff_ids)
      AND (gme.mentions_teacher OR gme.has_ustoz
           OR (gme.reply_to_user_id IS NOT NULL AND gme.reply_to_user_id = tg.t_tgid
               AND gme.reply_to_message_id IS DISTINCT FROM gme.telegram_thread_id))
  ),
  dq_ans AS (
    SELECT dq.tid, dq.gid, dq.q_at,
      (SELECT min(a.sent_at) FROM group_message_events a
       WHERE a.telegram_chat_id = dq.chat AND a.telegram_thread_id = dq.thread
         AND a.sent_at > dq.q_at AND a.profile_id IN (SELECT sid FROM staff_ids)) AS a_at
    FROM dq
  ),
  q_agg AS (
    SELECT tid, gid, count(*)::int AS questions,
      count(*) FILTER (WHERE a_at IS NOT NULL)::int AS answered,
      round(percentile_cont(0.5) WITHIN GROUP (ORDER BY EXTRACT(EPOCH FROM (a_at - q_at)) / 60.0)
            FILTER (WHERE a_at IS NOT NULL)::numeric, 1) AS median_wait_min
    FROM dq_ans GROUP BY tid, gid
  ),
  grading AS (
    SELECT g.teacher_id AS tid, g.id AS gid, count(*)::int AS graded,
      round(percentile_cont(0.5) WITHIN GROUP (
        ORDER BY EXTRACT(EPOCH FROM (hs.scored_at - hs.submitted_at)) / 60.0)::numeric, 1) AS grading_med_min,
      round(avg(100.0 * hs.score / NULLIF(ha.max_score, 0))::numeric, 0) AS avg_score_pct,
      round((100.0 * count(*) FILTER (WHERE hs.score = ha.max_score) / NULLIF(count(*), 0))::numeric, 0) AS pct_top,
      round((100.0 * count(*) FILTER (WHERE btrim(COALESCE(hs.score_feedback, '')) <> '') / NULLIF(count(*), 0))::numeric, 0) AS feedback_rate
    FROM homework_submissions hs
    JOIN homework_assignments ha ON ha.id = hs.assignment_id
    JOIN profiles pr ON pr.id = hs.user_id
    JOIN groups g ON g.id = pr.group_id AND g.teacher_id IS NOT NULL
    WHERE hs.scored_at >= _from AND hs.submitted_at IS NOT NULL AND hs.score IS NOT NULL
    GROUP BY g.teacher_id, g.id
  ),
  backlog AS (
    SELECT g.teacher_id AS tid, g.id AS gid, count(*)::int AS ungraded,
      round((EXTRACT(EPOCH FROM (now() - min(hs.submitted_at))) / 3600.0)::numeric, 1) AS oldest_pending_hours
    FROM homework_submissions hs
    JOIN profiles pr ON pr.id = hs.user_id
    JOIN groups g ON g.id = pr.group_id AND g.teacher_id IS NOT NULL
    WHERE hs.score IS NULL AND hs.submitted_at IS NOT NULL
    GROUP BY g.teacher_id, g.id
  ),
  resub AS (
    SELECT g.teacher_id AS tid, g.id AS gid,
      round((100.0 * count(*) FILTER (
        WHERE COALESCE(hs.attempt_number, 1) > 1
           OR jsonb_array_length(COALESCE(hs.previous_attempts, '[]'::jsonb)) > 0
      ) / NULLIF(count(*), 0))::numeric, 0) AS resubmit_rate
    FROM homework_submissions hs
    JOIN profiles pr ON pr.id = hs.user_id
    JOIN groups g ON g.id = pr.group_id AND g.teacher_id IS NOT NULL
    WHERE hs.submitted_at >= _from
    GROUP BY g.teacher_id, g.id
  ),
  lastact AS (
    SELECT tg.tid, tg.gid,
      (SELECT max(e.sent_at) FROM group_message_events e
       WHERE e.group_id = tg.gid
         AND (e.is_anon_admin OR (tg.t_tgid IS NOT NULL AND e.telegram_user_id = tg.t_tgid))) AS last_active
    FROM tg
  )
  SELECT tg.tid::uuid,
    (COALESCE(NULLIF(TRIM(CONCAT(p.name, ' ', COALESCE(p.last_name, ''))), ''), p.email))::text,
    p.telegram_username::text,
    tg.gid::uuid, tg.gname::text,
    COALESCE(h.active_days, 0)::int, p_days::int,
    COALESCE(h.active_min_by_day, ARRAY[]::int[]), COALESCE(h.week_active_min, 0)::int,
    COALESCE(h.messages_by_day, ARRAY[]::int[]), COALESCE(h.week_messages, 0)::int,
    COALESCE(q.questions, 0)::int, COALESCE(q.answered, 0)::int,
    (CASE WHEN COALESCE(q.questions, 0) > 0 THEN round(100.0 * q.answered / q.questions, 0) ELSE NULL END)::numeric,
    q.median_wait_min::numeric,
    COALESCE(gr.graded, 0)::int, gr.grading_med_min::numeric, COALESCE(bl.ungraded, 0)::int,
    gr.avg_score_pct::numeric, gr.pct_top::numeric, gr.feedback_rate::numeric,
    rs.resubmit_rate::numeric, bl.oldest_pending_hours::numeric,
    la.last_active::timestamptz
  FROM tg JOIN profiles p ON p.id = tg.tid
  LEFT JOIN hours_agg h ON h.gid = tg.gid AND h.tid = tg.tid
  LEFT JOIN q_agg q ON q.gid = tg.gid AND q.tid = tg.tid
  LEFT JOIN grading gr ON gr.gid = tg.gid AND gr.tid = tg.tid
  LEFT JOIN backlog bl ON bl.gid = tg.gid AND bl.tid = tg.tid
  LEFT JOIN resub rs ON rs.gid = tg.gid AND rs.tid = tg.tid
  LEFT JOIN lastact la ON la.gid = tg.gid AND la.tid = tg.tid
  ORDER BY 2, 5;
END;
$fx$;

-- teacher_daily_report: from 20260925062000_teacher_signals_topic_guard.sql; body md5 ef0733215c7de6faeb33f384d68ed39a
create or replace function public.teacher_daily_report()
returns table(
  teacher_id uuid, name text, telegram_id bigint,
  active_minutes int, messages int,
  answered_today int, open_questions int, median_wait_min numeric,
  graded_today int, grading_med_min numeric, avg_score_pct numeric,
  ungraded_backlog int, oldest_pending_hours numeric,
  last_active timestamptz
)
language plpgsql
stable
security definer
set search_path = public
as $fx$
#variable_conflict use_column
declare
  _today    date        := (now() at time zone 'Asia/Tashkent')::date;
  _daystart timestamptz := ((now() at time zone 'Asia/Tashkent')::date::timestamp) at time zone 'Asia/Tashkent';
  _qfrom    timestamptz := now() - interval '7 days';
begin
  -- service role (cron/edge fn, auth.uid() is null) or an admin/superadmin only.
  if not (auth.uid() is null
          or has_role(auth.uid(), 'admin'::app_role)
          or has_role(auth.uid(), 'superadmin'::app_role)) then
    raise exception 'not authorized';
  end if;

  return query
  with teachers as (
    select distinct ur.user_id as tid from user_roles ur where ur.role = 'teacher'::app_role
  ),
  staff_ids as (
    select distinct ur.user_id as sid from user_roles ur
    where ur.role in ('teacher'::app_role, 'admin'::app_role, 'superadmin'::app_role)
  ),
  tg as (
    select g.id as gid, g.teacher_id as tid, p.telegram_id as t_tgid
    from groups g
    join teachers t on t.tid = g.teacher_id
    join profiles p on p.id = g.teacher_id
    where exists (select 1 from group_message_events e where e.group_id = g.id)
  ),
  -- Active minutes TODAY: gap-session heuristic over the teacher's own messages (named or anon-admin).
  pair_msgs as (
    select tg.tid,
      e.sent_at - lag(e.sent_at) over (partition by tg.tid, tg.gid order by e.sent_at) as gap
    from group_message_events e
    join tg on tg.gid = e.group_id
    where (e.sent_at at time zone 'Asia/Tashkent')::date = _today
      and (e.is_anon_admin or (tg.t_tgid is not null and e.telegram_user_id = tg.t_tgid))
  ),
  active as (
    select tid,
      round(sum(
        (case when gap is not null and gap <= interval '10 minutes' then extract(epoch from gap) else 0 end
         + case when gap is null or gap > interval '10 minutes' then 60 else 0 end)) / 60.0)::int as active_minutes,
      count(*)::int as messages
    from pair_msgs group by tid
  ),
  -- Directed student questions in the last 7 days (tag / "ustoz" / reply to the teacher).
  dq as (
    select tg.tid, gme.telegram_chat_id as chat, gme.telegram_thread_id as thread, gme.sent_at as q_at
    from group_message_events gme
    join tg on tg.gid = gme.group_id
    where gme.sent_at >= _qfrom
      and gme.profile_id is not null
      and gme.profile_id not in (select sid from staff_ids)
      and (gme.mentions_teacher or gme.has_ustoz
           or (gme.reply_to_user_id is not null and gme.reply_to_user_id = tg.t_tgid
               and gme.reply_to_message_id is distinct from gme.telegram_thread_id))
  ),
  dq_ans as (
    select dq.tid, dq.q_at,
      (select min(a.sent_at) from group_message_events a
       where a.telegram_chat_id = dq.chat
         and a.telegram_thread_id is not distinct from dq.thread   -- NULL-safe (General-chat fix)
         and a.sent_at > dq.q_at
         and a.profile_id in (select sid from staff_ids)) as a_at
    from dq
  ),
  q_agg as (
    select tid,
      count(*) filter (where a_at is not null
                         and (a_at at time zone 'Asia/Tashkent')::date = _today)::int as answered_today,
      count(*) filter (where a_at is null)::int as open_questions,
      round(percentile_cont(0.5) within group (order by extract(epoch from (a_at - q_at)) / 60.0)
            filter (where a_at is not null
                     and (a_at at time zone 'Asia/Tashkent')::date = _today)::numeric, 1) as median_wait_min
    from dq_ans group by tid
  ),
  -- Homework graded TODAY (Tashkent).
  grading as (
    select g.teacher_id as tid, count(*)::int as graded_today,
      round(percentile_cont(0.5) within group (
        order by extract(epoch from (hs.scored_at - hs.submitted_at)) / 60.0)::numeric, 1) as grading_med_min,
      round(avg(100.0 * hs.score / nullif(ha.max_score, 0))::numeric, 0) as avg_score_pct
    from homework_submissions hs
    join homework_assignments ha on ha.id = hs.assignment_id
    join profiles pr on pr.id = hs.user_id
    join groups g on g.id = pr.group_id and g.teacher_id is not null
    where hs.scored_at >= _daystart and hs.submitted_at is not null and hs.score is not null
    group by g.teacher_id
  ),
  -- All-time ungraded backlog (work waiting on the teacher).
  backlog as (
    select g.teacher_id as tid, count(*)::int as ungraded,
      round((extract(epoch from (now() - min(hs.submitted_at))) / 3600.0)::numeric, 1) as oldest_pending_hours
    from homework_submissions hs
    join profiles pr on pr.id = hs.user_id
    join groups g on g.id = pr.group_id and g.teacher_id is not null
    where hs.score is null and hs.submitted_at is not null
    group by g.teacher_id
  ),
  lastact as (
    select tg.tid,
      max((select max(e.sent_at) from group_message_events e
           where e.group_id = tg.gid
             and (e.is_anon_admin or (tg.t_tgid is not null and e.telegram_user_id = tg.t_tgid)))) as last_active
    from tg group by tg.tid
  )
  select t.tid,
    (coalesce(nullif(trim(concat(p.name, ' ', coalesce(p.last_name, ''))), ''), p.email))::text,
    p.telegram_id::bigint,
    coalesce(a.active_minutes, 0)::int, coalesce(a.messages, 0)::int,
    coalesce(q.answered_today, 0)::int, coalesce(q.open_questions, 0)::int, q.median_wait_min::numeric,
    coalesce(gr.graded_today, 0)::int, gr.grading_med_min::numeric, gr.avg_score_pct::numeric,
    coalesce(bl.ungraded, 0)::int, bl.oldest_pending_hours::numeric,
    la.last_active::timestamptz
  from teachers t
  join profiles p on p.id = t.tid
  left join active  a  on a.tid  = t.tid
  left join q_agg   q  on q.tid  = t.tid
  left join grading gr on gr.tid = t.tid
  left join backlog bl on bl.tid = t.tid
  left join lastact la on la.tid = t.tid
  order by 2;
end;
$fx$;

-- teacher_nudge_signals: from 20260925062000_teacher_signals_topic_guard.sql; body md5 7f94d545b538b3a8f26dcf5373ed75d6
create or replace function public.teacher_nudge_signals(p_q_hours int default 8, p_window_days int default 3)
returns table(
  teacher_id uuid, telegram_id bigint, preferred_locale text, notifications_enabled boolean,
  waiting_questions int, oldest_wait_hours numeric,
  pending_homework int, last_active timestamptz, offline_hours numeric
)
language sql stable security definer set search_path = public
as $fx$
  with teachers as (
    select p.id as tid, p.telegram_id, p.preferred_locale, p.notifications_enabled
    from profiles p
    join user_roles ur on ur.user_id = p.id and ur.role = 'teacher'::app_role
    where p.telegram_id is not null
  ),
  staff_ids as (
    select distinct ur.user_id as sid from user_roles ur
    where ur.role in ('teacher'::app_role, 'admin'::app_role, 'superadmin'::app_role)
  ),
  my_groups as (
    select g.id as gid, g.teacher_id as tid, t.telegram_id as t_tgid
    from groups g join teachers t on t.tid = g.teacher_id
  ),
  -- directed student questions in the window that are old enough to nudge
  dq as (
    select mg.tid, gme.telegram_chat_id as chat, gme.telegram_thread_id as thread, gme.sent_at as q_at
    from group_message_events gme
    join my_groups mg on mg.gid = gme.group_id
    where gme.sent_at >= now() - make_interval(days => p_window_days)
      and gme.sent_at <= now() - make_interval(hours => p_q_hours)
      and gme.profile_id is not null and gme.profile_id not in (select sid from staff_ids)
      and (gme.mentions_teacher or gme.has_ustoz
           or (gme.reply_to_user_id is not null and mg.t_tgid is not null and gme.reply_to_user_id = mg.t_tgid
               and gme.reply_to_message_id is distinct from gme.telegram_thread_id))
  ),
  -- ...that STILL have no staff reply after them in the same thread
  dq_open as (
    select dq.tid, dq.q_at
    from dq
    where not exists (
      select 1 from group_message_events a
      where a.telegram_chat_id = dq.chat and a.telegram_thread_id = dq.thread
        and a.sent_at > dq.q_at and a.profile_id in (select sid from staff_ids)
    )
  ),
  q_agg as (
    select tid, count(*)::int as waiting_questions,
      round((extract(epoch from (now() - min(q_at))) / 3600.0)::numeric, 1) as oldest_wait_hours
    from dq_open group by tid
  ),
  pend as (
    select g.teacher_id as tid, count(*)::int as pending_homework
    from homework_submissions hs
    join profiles pr on pr.id = hs.user_id
    join groups g on g.id = pr.group_id and g.teacher_id is not null
    where hs.score is null and hs.submitted_at is not null
    group by g.teacher_id
  ),
  lastact as (
    select t.tid,
      greatest(
        coalesce((select max(e.sent_at) from group_message_events e
                  join my_groups mg on mg.gid = e.group_id and mg.tid = t.tid
                  where (e.is_anon_admin or (t.telegram_id is not null and e.telegram_user_id = t.telegram_id))),
                 'epoch'::timestamptz),
        coalesce((select max(hs.scored_at) from homework_submissions hs where hs.scored_by = t.tid), 'epoch'::timestamptz),
        coalesce((select max(ae.created_at) from auth_events ae where ae.user_id = t.tid), 'epoch'::timestamptz)
      ) as last_active
    from teachers t
  )
  select t.tid, t.telegram_id, t.preferred_locale, t.notifications_enabled,
    coalesce(q.waiting_questions, 0), q.oldest_wait_hours,
    coalesce(pe.pending_homework, 0),
    nullif(la.last_active, 'epoch'::timestamptz),
    case when la.last_active > 'epoch'::timestamptz
         then round((extract(epoch from (now() - la.last_active)) / 3600.0)::numeric, 1)
         else null end
  from teachers t
  left join q_agg q on q.tid = t.tid
  left join pend pe on pe.tid = t.tid
  left join lastact la on la.tid = t.tid;
$fx$;

-- teacher_weekly_self: from 20260925062000_teacher_signals_topic_guard.sql; body md5 a91406c7efbf6f8fcbb2afd7d6ee75dc
CREATE OR REPLACE FUNCTION public.teacher_weekly_self(uid uuid, p_days integer DEFAULT 7)
 RETURNS TABLE(graded integer, grading_med_min numeric, on_time_pct numeric, ungraded_backlog integer, oldest_pending_hours numeric, feedback_rate numeric, avg_score_pct numeric, questions integer, answered integer, answer_rate numeric, median_wait_min numeric, active_days integer, days_window integer, week_messages integer, last_active timestamp with time zone)
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
as $fx$
#variable_conflict use_column
declare
  _from timestamptz := now() - make_interval(days => p_days);
  _tgid bigint;
begin
  if not (auth.role() = 'service_role' or auth.uid() = uid
          or has_role(auth.uid(), 'admin'::app_role)
          or has_role(auth.uid(), 'superadmin'::app_role)) then
    raise exception 'not allowed';
  end if;

  select p.telegram_id into _tgid from profiles p where p.id = uid;

  return query
  with
  staff_ids as (
    select distinct ur.user_id as sid from user_roles ur
    where ur.role in ('teacher'::app_role, 'admin'::app_role, 'superadmin'::app_role)
  ),
  my_groups as (
    select g.id as gid from groups g where g.teacher_id = uid
  ),
  -- grading YOU did in the window + turnaround / on-time / quality signals
  grading as (
    select
      count(*)::int as graded,
      round(percentile_cont(0.5) within group (
        order by extract(epoch from (hs.scored_at - hs.submitted_at)) / 60.0)::numeric, 1) as grading_med_min,
      round((100.0 * count(*) filter (
        where hs.scored_at - hs.submitted_at <= interval '24 hours') / nullif(count(*), 0))::numeric, 0) as on_time_pct,
      round((100.0 * count(*) filter (
        where btrim(coalesce(hs.score_feedback, '')) <> '') / nullif(count(*), 0))::numeric, 0) as feedback_rate,
      round(avg(100.0 * hs.score / nullif(ha.max_score, 0))::numeric, 0) as avg_score_pct
    from homework_submissions hs
    join homework_assignments ha on ha.id = hs.assignment_id
    where hs.scored_by = uid and hs.scored_at >= _from
      and hs.submitted_at is not null and hs.score is not null
  ),
  -- current backlog waiting on this teacher's groups
  backlog as (
    select count(*)::int as ungraded_backlog,
      round((extract(epoch from (now() - min(hs.submitted_at))) / 3600.0)::numeric, 1) as oldest_pending_hours
    from homework_submissions hs
    join profiles pr on pr.id = hs.user_id
    join my_groups mg on mg.gid = pr.group_id
    where hs.score is null and hs.submitted_at is not null
  ),
  -- directed student questions in this teacher's groups
  dq as (
    select gme.telegram_chat_id as chat, gme.telegram_thread_id as thread, gme.sent_at as q_at
    from group_message_events gme
    join my_groups mg on mg.gid = gme.group_id
    where gme.sent_at >= _from
      and gme.profile_id is not null and gme.profile_id not in (select sid from staff_ids)
      and (gme.mentions_teacher or gme.has_ustoz
           or (gme.reply_to_user_id is not null and _tgid is not null and gme.reply_to_user_id = _tgid
               and gme.reply_to_message_id is distinct from gme.telegram_thread_id))
  ),
  dq_ans as (
    select dq.q_at,
      (select min(a.sent_at) from group_message_events a
        where a.telegram_chat_id = dq.chat and a.telegram_thread_id = dq.thread
          and a.sent_at > dq.q_at and a.profile_id in (select sid from staff_ids)) as a_at
    from dq
  ),
  q_agg as (
    select count(*)::int as questions,
      count(*) filter (where a_at is not null)::int as answered,
      round(percentile_cont(0.5) within group (order by extract(epoch from (a_at - q_at)) / 60.0)
            filter (where a_at is not null)::numeric, 1) as median_wait_min
    from dq_ans
  ),
  -- this teacher's own messages in their groups (anon-admin OR own named account)
  acts as (
    select (e.sent_at at time zone 'Asia/Tashkent')::date as d, e.sent_at
    from group_message_events e
    join my_groups mg on mg.gid = e.group_id
    where e.sent_at >= _from
      and (e.is_anon_admin or (_tgid is not null and e.telegram_user_id = _tgid))
  ),
  act_agg as (
    select count(distinct d)::int as active_days, count(*)::int as week_messages from acts
  ),
  lastact as (select max(sent_at) as last_active from acts)
  select
    coalesce(g.graded, 0)::int, g.grading_med_min, g.on_time_pct,
    coalesce(b.ungraded_backlog, 0)::int, b.oldest_pending_hours,
    g.feedback_rate, g.avg_score_pct,
    coalesce(q.questions, 0)::int, coalesce(q.answered, 0)::int,
    (case when coalesce(q.questions, 0) > 0 then round(100.0 * q.answered / q.questions, 0) else null end)::numeric,
    q.median_wait_min,
    coalesce(a.active_days, 0)::int, p_days::int, coalesce(a.week_messages, 0)::int,
    la.last_active
  from grading g
  cross join backlog b
  cross join q_agg q
  cross join act_agg a
  cross join lastact la;
end;
$fx$;

-- award_teacher_engagement_xp: from 20260925062000_teacher_signals_topic_guard.sql; body md5 934a501ed3009c21345a333f7048d7a5
create or replace function public.award_teacher_engagement_xp(p_lookback_hours int default 26)
returns void
language plpgsql
security definer
set search_path to 'public'
as $fx$
declare
  _from timestamptz := now() - make_interval(hours => p_lookback_hours);
begin
  -- (A) Answered-question XP: +8 per directed question answered by staff within 6h.
  perform public.award_xp(a.tid, 8, 'teacher_answer',
      'tanswer:' || a.chat::text || ':' || ((extract(epoch from a.q_at) * 1000000)::bigint)::text)
  from (
    with staff_ids as (
      select distinct ur.user_id as sid from user_roles ur
      where ur.role in ('teacher'::app_role, 'admin'::app_role, 'superadmin'::app_role)
    ),
    tg as (
      select g.id as gid, g.teacher_id as tid, p.telegram_id as t_tgid
      from groups g join profiles p on p.id = g.teacher_id
      where g.teacher_id is not null
    ),
    dq as (
      select tg.tid, gme.telegram_chat_id as chat, gme.telegram_thread_id as thread, gme.sent_at as q_at
      from group_message_events gme
      join tg on tg.gid = gme.group_id
      where gme.sent_at >= _from
        and gme.profile_id is not null and gme.profile_id not in (select sid from staff_ids)
        and (gme.mentions_teacher or gme.has_ustoz
             or (gme.reply_to_user_id is not null and tg.t_tgid is not null and gme.reply_to_user_id = tg.t_tgid
                 and gme.reply_to_message_id is distinct from gme.telegram_thread_id))
    ),
    answered as (
      select dq.tid, dq.chat, dq.q_at,
        (select min(x.sent_at) from group_message_events x
         where x.telegram_chat_id = dq.chat and x.telegram_thread_id = dq.thread
           and x.sent_at > dq.q_at and x.profile_id in (select sid from staff_ids)) as a_at
      from dq
    )
    select tid, chat, q_at from answered
    where a_at is not null and (a_at - q_at) <= interval '6 hours'
  ) a;

  -- (B) Queue-clear XP: +20 once per Tashkent-day to teachers who graded today AND now have 0 backlog.
  perform public.award_xp(t.tid, 20, 'teacher_queue_clear',
      'tqueueclear:' || t.tid::text || ':' || ((now() at time zone 'Asia/Tashkent')::date)::text)
  from (
    select g.teacher_id as tid
    from groups g
    where g.teacher_id is not null
    group by g.teacher_id
    having exists (
        select 1 from homework_submissions hs
        where hs.scored_by = g.teacher_id
          and (hs.scored_at at time zone 'Asia/Tashkent')::date = (now() at time zone 'Asia/Tashkent')::date)
      and not exists (
        select 1 from homework_submissions hs2
        join profiles pr on pr.id = hs2.user_id
        join groups g2 on g2.id = pr.group_id
        where g2.teacher_id = g.teacher_id and hs2.score is null and hs2.submitted_at is not null)
  ) t;
end;
$fx$;

-- xp_on_student_module_impact: from 20260708110000_teacher_impact_xp.sql; body md5 0b8a63e7a60eb204e1c95f97863e9839
create or replace function public.xp_on_student_module_impact()
returns trigger
language plpgsql
security definer
set search_path to 'public'
as $fx$
declare
  _teacher uuid;
begin
  select g.teacher_id into _teacher
  from public.profiles p
  join public.groups g on g.id = p.group_id
  where p.id = new.profile_id;

  if _teacher is not null then
    begin
      perform public.award_xp(_teacher, 25, 'teacher_impact',
        'timpact:mod:' || new.profile_id::text || ':' || new.module_id::text);
    exception when others then
      raise warning 'xp_on_student_module_impact skipped (%, %): %', new.profile_id, new.module_id, sqlerrm;
    end;
  end if;
  return new;
end;
$fx$;

