// This file is automatically generated. Do not edit it directly.
// [hand-edit] Backend calls are routed through a same-origin `/sb` proxy (see
// src/lib/supabaseBase.ts + vercel.json) so networks that block *.supabase.co
// can still reach the backend. Realtime uses a dedicated direct-host client.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { SB_BASE, SB_DIRECT_URL } from '@/lib/supabaseBase';

const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Primary client — auth / data / storage / functions.invoke all flow through the
// same-origin `/sb` proxy.
export const supabase = createClient<Database>(SB_BASE, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Realtime (websockets) can't ride the Vercel HTTP rewrite, so this dedicated
// client talks to the Supabase host DIRECTLY. It does not manage auth (distinct
// storageKey + no persist) so it can't fight the primary GoTrueClient over the
// stored session; instead we push the primary session's JWT into it below, so
// RLS-gated realtime stays authorized. Use ONLY for realtime subscriptions
// (currently just the admin KnowledgeManager) — everything else uses `supabase`.
export const supabaseRealtime = createClient<Database>(SB_DIRECT_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: false,
    autoRefreshToken: false,
    storageKey: 'sb-rt-noauth',
  }
});
supabase.auth.onAuthStateChange((_event, session) => {
  supabaseRealtime.realtime.setAuth(session?.access_token ?? null);
});
